name: gift_record
description: 礼金本 - 婚宴寿宴礼金记录
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  screenshot: ^3.0.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true